## Data Exploration

In [17]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_excel("../data/raw/ethiopia_fi_unified_data.xlsx")
print(df.columns.tolist())
df.head()

['record_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [ ]:
print(df['record_type'].value_counts())
print(df["pillar"].value_counts())
print(df["source_type"].value_counts())
print(df["confidence"].value_counts())

record_type
observation    30
event          10
target          3
Name: count, dtype: int64
pillar
ACCESS           16
USAGE            11
GENDER            5
AFFORDABILITY     1
Name: count, dtype: int64
source_type
operator      15
survey        10
regulator      7
research       4
policy         3
calculated     2
news           2
Name: count, dtype: int64
confidence
high      40
medium     3
Name: count, dtype: int64
indicator_code
ACC_4G_COV             4.651163
ACC_FAYDA              9.302326
ACC_MM_ACCOUNT         4.651163
ACC_MOBILE_PEN         2.325581
ACC_OWNERSHIP         16.279070
AFF_DATA_INCOME        2.325581
EVT_CROSSOVER          2.325581
EVT_ETHIOPAY           2.325581
EVT_FAYDA              2.325581
EVT_FX_REFORM          2.325581
EVT_MPESA              2.325581
EVT_MPESA_INTEROP      2.325581
EVT_NFIS2              2.325581
EVT_SAFARICOM          2.325581
EVT_SAFCOM_PRICE       2.325581
EVT_TELEBIRR           2.325581
GEN_GAP_ACC            4.651163
GEN_GAP_MOBILE         2.325581
GEN_MM_SHARE           4.651163
USG_ACTIVE_RATE        2.325581
USG_ATM_COUNT          2.325581
USG_ATM_VALUE          2.325581
USG_CROSSOVER          2.325581
USG_MPESA_ACTIVE       2.325581
USG_MPESA_USERS        2.325581
USG_P2P_COUNT          4.651163
USG_P2P_VALUE          2.325581
USG_TELEBIRR_USERS     2.325581
USG_TELEBIRR_VALUE     2.325581
dtype: float64

In [28]:
coverage = df.groupby('indicator_code').size() / len(df) * 100
print(coverage)

indicator_code
ACC_4G_COV             4.651163
ACC_FAYDA              9.302326
ACC_MM_ACCOUNT         4.651163
ACC_MOBILE_PEN         2.325581
ACC_OWNERSHIP         16.279070
AFF_DATA_INCOME        2.325581
EVT_CROSSOVER          2.325581
EVT_ETHIOPAY           2.325581
EVT_FAYDA              2.325581
EVT_FX_REFORM          2.325581
EVT_MPESA              2.325581
EVT_MPESA_INTEROP      2.325581
EVT_NFIS2              2.325581
EVT_SAFARICOM          2.325581
EVT_SAFCOM_PRICE       2.325581
EVT_TELEBIRR           2.325581
GEN_GAP_ACC            4.651163
GEN_GAP_MOBILE         2.325581
GEN_MM_SHARE           4.651163
USG_ACTIVE_RATE        2.325581
USG_ATM_COUNT          2.325581
USG_ATM_VALUE          2.325581
USG_CROSSOVER          2.325581
USG_MPESA_ACTIVE       2.325581
USG_MPESA_USERS        2.325581
USG_P2P_COUNT          4.651163
USG_P2P_VALUE          2.325581
USG_TELEBIRR_USERS     2.325581
USG_TELEBIRR_VALUE     2.325581
dtype: float64

In [22]:
df_sheet2 = pd.read_excel("../data/raw/ethiopia_fi_unified_data.xlsx", sheet_name=1)
df_sheet2.head(3)

,record_id,parent_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,IMP_0001,EVT_0001,impact_link,NaN,ACCESS,Telebirr effect on Account Ownership,NaN,NaN,15.0,NaN,...,increase,high,15.0,12,literature,Kenya,Example_Trainee,2025-01-20,NaN,Kenya M-Pesa showed +20pp over 5 years
1,IMP_0002,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on Telebirr Users,NaN,NaN,NaN,NaN,...,increase,high,NaN,3,empirical,NaN,Example_Trainee,2025-01-20,NaN,Direct subscriber acquisition
2,IMP_0003,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on P2P Transactions,NaN,NaN,25.0,NaN,...,increase,high,25.0,6,empirical,NaN,Example_Trainee,2025-01-20,NaN,New digital payment channel

### Step 1.2: Understand Structure

Check temporal range:

In [4]:
obs['observation_date'] = pd.to_datetime(obs['observation_date'])
print(obs['observation_date'].min(), obs['observation_date'].max())

2014-12-31 00:00:00 2025-12-31 00:00:00

List indicators:

In [30]:
print(obs['indicator_code'].unique())

<StringArray>
[     'ACC_OWNERSHIP',     'ACC_MM_ACCOUNT',         'ACC_4G_COV',
     'ACC_MOBILE_PEN',          'ACC_FAYDA',      'USG_P2P_COUNT',
      'USG_P2P_VALUE',      'USG_ATM_COUNT',      'USG_ATM_VALUE',
      'USG_CROSSOVER', 'USG_TELEBIRR_USERS', 'USG_TELEBIRR_VALUE',
    'USG_MPESA_USERS',   'USG_MPESA_ACTIVE',    'USG_ACTIVE_RATE',
    'AFF_DATA_INCOME',        'GEN_GAP_ACC',       'GEN_MM_SHARE',
     'GEN_GAP_MOBILE']
Length: 19, dtype: str

### Step 1.3: Enriched Dataset

In [34]:
df_enriched = pd.read_csv("../data/processed/ethiopia_fi_unified_data_enriched.csv")
df_enriched.tail()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes,event_name,event_date,id,parent_id
40,EVT_0008,event,infrastructure,NaN,EthioPay Instant Payment System Launch,EVT_ETHIOPAY,NaN,NaN,Launched,categorical,...,NaN,Example_Trainee,1/20/2025 0:00,NaN,National real-time payment system,NaN,NaN,NaN,NaN,NaN
41,EVT_0009,event,policy,NaN,NFIS-II Strategy Launch,EVT_NFIS2,NaN,NaN,Launched,categorical,...,NaN,Example_Trainee,1/20/2025 0:00,NaN,5-year national financial inclusion strategy,NaN,NaN,NaN,NaN,NaN
42,EVT_0010,event,pricing,NaN,Safaricom Ethiopia Price Increase,EVT_SAFCOM_PRICE,NaN,NaN,Implemented,categorical,...,NaN,Example_Trainee,1/20/2025 0:00,NaN,Data and voice prices increased 20-82%,NaN,NaN,NaN,NaN,NaN
43,REC_0031,observation,NaN,ACCESS,Number of automated teller machines (ATMs),ACC_ATM,higher_better,NaN,10.07,"Per 100,000 adults",...,NaN,Example_Trainee,2/3/2026 12:00,NaN,"10.07/100,000 Adults",NaN,NaN,NaN,NaN,NaN
44,EVT_0011,event,product_launch,NaN,Dashen Bank SuperApp Launch,EVT_DASHEN_SUPERAPP,higher_better,NaN,Launched,categorical,...,NaN,Example_Trainee,2/3/2026 12:00,NaN,Dashen Bank has launched a banking Super App,NaN,NaN,NaN,NaN,NaN